/**
 * 거래 지역 · 동네(Area) 목록 — 피드 표시는 `getLocationLabel(regionId, cityId)` (영문 라벨).
 * city `id`는 저장·API 호환용으로 안정적으로 유지 (기존 m1, q1 등 우선).
 */

export const REGIONS = [
  {
    id: "manila",
    name: "Manila",
    cities: [
      { id: "m1", name: "Malate" },
      { id: "m2", name: "Makati" },
      { id: "m3", name: "Ermita" },
      { id: "m4", name: "Binondo" },
      { id: "m5", name: "Quiapo" },
      { id: "m6", name: "Intramuros" },
      { id: "m7", name: "Sampaloc" },
      { id: "m8", name: "Santa Mesa" },
      { id: "m9", name: "Tondo" },
      { id: "m10", name: "San Nicolas" },
      { id: "m11", name: "Santa Cruz" },
      { id: "m12", name: "San Miguel" },
      { id: "m13", name: "Paco" },
      { id: "m14", name: "Pandacan" },
      { id: "m15", name: "Santa Ana" },
      { id: "m16", name: "Port Area" },
      { id: "m17", name: "San Andres Bukid" },
      { id: "m18", name: "Taguig – BGC" },
      { id: "m19", name: "Taguig – Upper Taguig" },
      { id: "m20", name: "Pasig – Ortigas Center" },
      { id: "m21", name: "Pasig – Kapitolyo" },
      { id: "m22", name: "Pasig – San Antonio" },
      { id: "m23", name: "Mandaluyong – Shaw" },
      { id: "m24", name: "Mandaluyong – Highway Hills" },
      { id: "m25", name: "Parañaque – BF Homes" },
      { id: "m26", name: "Parañaque – Baclaran" },
      { id: "m27", name: "Las Piñas" },
      { id: "m28", name: "Muntinlupa – Alabang" },
      { id: "m29", name: "Marikina" },
      { id: "m30", name: "Caloocan North" },
      { id: "m31", name: "Caloocan South" },
      { id: "m32", name: "Valenzuela" },
      { id: "m33", name: "Malabon" },
      { id: "m34", name: "Navotas" },
      { id: "m35", name: "San Juan – Greenhills" },
      { id: "m36", name: "Pasay – MOA Area" },
      { id: "m37", name: "Pasay – Taft" },
      { id: "m38", name: "Pateros" },
      { id: "m39", name: "Makati – Poblacion" },
      { id: "m40", name: "Makati – Guadalupe" },
    ],
  },
  {
    id: "quezon",
    name: "Quezon City",
    cities: [
      { id: "q1", name: "Diliman" },
      { id: "q2", name: "Fairview" },
      { id: "q3", name: "Cubao" },
      { id: "q4", name: "Katipunan" },
      { id: "q5", name: "Commonwealth" },
      { id: "q6", name: "Novaliches Proper" },
      { id: "q7", name: "North Fairview" },
      { id: "q8", name: "Batasan Hills" },
      { id: "q9", name: "Eastwood City" },
      { id: "q10", name: "Loyola Heights" },
      { id: "q11", name: "Teachers Village" },
      { id: "q12", name: "UP Village" },
      { id: "q13", name: "Krus na Ligas" },
      { id: "q14", name: "Project 6" },
      { id: "q15", name: "Project 7" },
      { id: "q16", name: "Project 8" },
      { id: "q17", name: "Tandang Sora" },
      { id: "q18", name: "Sauyo" },
      { id: "q19", name: "Baesa" },
      { id: "q20", name: "Bagbag" },
      { id: "q21", name: "Holy Spirit" },
      { id: "q22", name: "Bago Bantay" },
      { id: "q23", name: "South Triangle" },
      { id: "q24", name: "West Triangle" },
      { id: "q25", name: "Galas" },
      { id: "q26", name: "Doña Imelda" },
      { id: "q27", name: "San Bartolome" },
      { id: "q28", name: "San Jose" },
      { id: "q29", name: "Bagong Silangan" },
      { id: "q30", name: "Payatas" },
      { id: "q31", name: "Pasong Tamo QC" },
      { id: "q32", name: "Masagana" },
      { id: "q33", name: "Vasra" },
      { id: "q34", name: "Balara" },
      { id: "q35", name: "Old Balara" },
      { id: "q36", name: "Capitol Hills" },
      { id: "q37", name: "Ugong Norte" },
      { id: "q38", name: "Bagumbayan" },
      { id: "q39", name: "Libis" },
      { id: "q40", name: "White Plains" },
    ],
  },
  {
    id: "cebu",
    name: "Cebu",
    cities: [
      { id: "c1", name: "Lahug" },
      { id: "c2", name: "Mandaue" },
      { id: "c3", name: "IT Park" },
      { id: "c4", name: "Mabolo" },
      { id: "c5", name: "Banilad" },
      { id: "c6", name: "Cebu Business Park" },
      { id: "c7", name: "Talamban" },
      { id: "c8", name: "Guadalupe" },
      { id: "c9", name: "Ramos" },
      { id: "c10", name: "Capitol Site" },
      { id: "c11", name: "Colon" },
      { id: "c12", name: "Carbon" },
      { id: "c13", name: "Sambag I" },
      { id: "c14", name: "Sambag II" },
      { id: "c15", name: "Carreta" },
      { id: "c16", name: "Banawa" },
      { id: "c17", name: "Inayawan" },
      { id: "c18", name: "Punta Princesa" },
      { id: "c19", name: "Labangon" },
      { id: "c20", name: "Pardo" },
      { id: "c21", name: "Busay" },
      { id: "c22", name: "Apas" },
      { id: "c23", name: "Camputhaw" },
      { id: "c24", name: "Cebu Port" },
      { id: "c25", name: "North Reclamation" },
      { id: "c26", name: "Consolacion" },
      { id: "c27", name: "Liloan" },
      { id: "c28", name: "Lapu-Lapu" },
      { id: "c29", name: "Mactan" },
      { id: "c30", name: "Talisay" },
      { id: "c31", name: "Minglanilla" },
      { id: "c32", name: "Naga" },
      { id: "c33", name: "Toledo" },
      { id: "c34", name: "Carcar" },
      { id: "c35", name: "Cordova" },
    ],
  },
  {
    id: "angeles",
    name: "Angeles",
    cities: [
      { id: "a1", name: "Balibago" },
      { id: "a2", name: "Cutcut" },
      { id: "a3", name: "Pulung Maragul" },
      { id: "a4", name: "Sapang Bato" },
      { id: "a5", name: "Capaya" },
      { id: "a6", name: "Mining" },
      { id: "a7", name: "Pandan" },
      { id: "a8", name: "Pulungbulu" },
      { id: "a9", name: "Amsic" },
      { id: "a10", name: "Malaba" },
      { id: "a11", name: "Sto. Domingo" },
      { id: "a12", name: "Pulung Cacutud" },
      { id: "a13", name: "Anunas" },
      { id: "a14", name: "Margot" },
      { id: "a15", name: "Ninoy Aquino" },
      { id: "a16", name: "Malabanias" },
      { id: "a17", name: "Friendship" },
      { id: "a18", name: "Lourdes North West" },
      { id: "a19", name: "Lourdes Sur East" },
      { id: "a20", name: "Salapungan" },
      { id: "a21", name: "Tabun" },
      { id: "a22", name: "Virgen delos Remedios" },
      { id: "a23", name: "Agapito del Rosario" },
      { id: "a24", name: "Amsic Industrial" },
      { id: "a25", name: "Claro M. Recto" },
      { id: "a26", name: "Lazatin" },
      { id: "a27", name: "Sta. Teresita" },
      { id: "a28", name: "Sta. Trinidad" },
    ],
  },
] as const;
