import {
  MYPAGE_HOME_BODY_CLASS,
  MYPAGE_HOME_BOTTOM_NAV_CLEARANCE_CLASS,
  MYPAGE_HOME_BODY_TEXT_CLASS,
  MYPAGE_HOME_CARD_CLASS,
  MYPAGE_HOME_CARD_PAD_CLASS,
  MYPAGE_HOME_HANDLE_CLASS,
  MYPAGE_HOME_MENU_TITLE_CLASS,
  MYPAGE_HOME_META_TEXT_CLASS,
  MYPAGE_HOME_PAGE_BG_CLASS,
  MYPAGE_HOME_PROFILE_CARD_CLASS,
  MYPAGE_HOME_PROFILE_NAME_CLASS,
  MYPAGE_HOME_SECTION_LABEL_CLASS,
  MYPAGE_HOME_STAT_VALUE_ACCENT_CLASS,
  MYPAGE_HOME_STAT_VALUE_CLASS,
} from "@/lib/ui/mypage-home-starbucks-styles";

export const MYINFO_TYPO = {
  pageTitle: MYPAGE_HOME_PROFILE_NAME_CLASS,
  profileName: MYPAGE_HOME_PROFILE_NAME_CLASS,
  sectionTitle: MYPAGE_HOME_SECTION_LABEL_CLASS,
  menuTitle: MYPAGE_HOME_MENU_TITLE_CLASS,
  subText: MYPAGE_HOME_BODY_TEXT_CLASS,
  metaText: MYPAGE_HOME_META_TEXT_CLASS,
  handle: MYPAGE_HOME_HANDLE_CLASS,
  number: MYPAGE_HOME_STAT_VALUE_CLASS,
  numberAccent: MYPAGE_HOME_STAT_VALUE_ACCENT_CLASS,
} as const;

export const MYINFO_SURFACE = {
  page: MYPAGE_HOME_PAGE_BG_CLASS,
  container: MYPAGE_HOME_BODY_CLASS.replace(` pt-2 ${MYPAGE_HOME_BOTTOM_NAV_CLEARANCE_CLASS}`, ""),
  card: MYPAGE_HOME_CARD_CLASS,
  profileCard: MYPAGE_HOME_PROFILE_CARD_CLASS,
  cardPad: MYPAGE_HOME_CARD_PAD_CLASS,
  row: "min-h-[52px]",
} as const;

