/**
 * 46단계: 런칭 점검 항목 mock (38 액션, 39 docs, 33 deployment, 35 incident, 37 report 연계)
 */

import type {
  LaunchReadinessItem,
  LaunchReadinessPhase,
  LaunchReadinessArea,
  LaunchReadinessStatus,
} from "@/lib/types/launch-readiness";

const ITEMS: LaunchReadinessItem[] = [
  {
    id: "lri-1",
    templateId: "lct-1",
    phase: "pre_launch",
    area: "user_app",
    title: "회원가입/로그인 E2E 검증",
    gateType: "must_have",
    status: "ready",
    priority: "critical",
    ownerAdminId: "admin1",
    ownerAdminNickname: "관리자",
    dueDate: new Date().toISOString().slice(0, 10),
    blockerReason: null,
    note: "",
    linkedType: null,
    linkedId: null,
    checkedAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "lri-2",
    templateId: "lct-2",
    phase: "pre_launch",
    area: "user_app",
    title: "상품 등록/수정/삭제 검증",
    gateType: "must_have",
    status: "ready",
    priority: "high",
    ownerAdminId: "admin1",
    ownerAdminNickname: "관리자",
    dueDate: null,
    blockerReason: null,
    note: "",
    linkedType: null,
    linkedId: null,
    checkedAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "lri-3",
    templateId: "lct-3",
    phase: "pre_launch",
    area: "admin_console",
    title: "관리자 로그인 및 권한 검증",
    gateType: "must_have",
    status: "in_progress",
    priority: "critical",
    ownerAdminId: "admin1",
    ownerAdminNickname: "관리자",
    dueDate: new Date(Date.now() + 3 * 86400000).toISOString().slice(0, 10),
    blockerReason: null,
    note: "역할 2종 추가 검증 중",
    linkedType: null,
    linkedId: null,
    checkedAt: null,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "lri-4",
    templateId: "lct-4",
    phase: "pre_launch",
    area: "recommendation",
    title: "홈 피드·추천 API 정상 응답",
    gateType: "must_have",
    status: "ready",
    priority: "high",
    ownerAdminId: null,
    ownerAdminNickname: null,
    dueDate: null,
    blockerReason: null,
    note: "",
    linkedType: "deployment",
    linkedId: "rd-1",
    checkedAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "lri-5",
    templateId: "lct-5",
    phase: "pre_launch",
    area: "moderation",
    title: "신고 접수·제재 플로우 검증",
    gateType: "must_have",
    status: "ready",
    priority: "high",
    ownerAdminId: null,
    ownerAdminNickname: null,
    dueDate: null,
    blockerReason: null,
    note: "",
    linkedType: null,
    linkedId: null,
    checkedAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "lri-6",
    templateId: "lct-6",
    phase: "pre_launch",
    area: "points_payment",
    title: "포인트 충전·사용 검증",
    gateType: "must_have",
    status: "blocked",
    priority: "high",
    ownerAdminId: "admin2",
    ownerAdminNickname: "운영B",
    dueDate: new Date(Date.now() + 7 * 86400000).toISOString().slice(0, 10),
    blockerReason: "결제 PG 샌드박스 이슈 대기 중",
    note: "",
    linkedType: "action_item",
    linkedId: "oai-1",
    checkedAt: null,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "lri-7",
    templateId: "lct-8",
    phase: "pre_launch",
    area: "docs_sop",
    title: "운영 SOP·플레이북 최신화",
    gateType: "must_have",
    status: "in_progress",
    priority: "high",
    ownerAdminId: "admin1",
    ownerAdminNickname: "관리자",
    dueDate: null,
    blockerReason: null,
    note: "",
    linkedType: "document",
    linkedId: "od-1",
    checkedAt: null,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "lri-8",
    templateId: "lct-9",
    phase: "pre_launch",
    area: "monitoring_automation",
    title: "모니터링·알림 연동 검증",
    gateType: "must_have",
    status: "ready",
    priority: "critical",
    ownerAdminId: null,
    ownerAdminNickname: null,
    dueDate: null,
    blockerReason: null,
    note: "",
    linkedType: null,
    linkedId: null,
    checkedAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "lri-9",
    templateId: "lct-10",
    phase: "pre_launch",
    area: "security",
    title: "보안 점검 placeholder",
    gateType: "must_have",
    status: "not_ready",
    priority: "critical",
    ownerAdminId: null,
    ownerAdminNickname: null,
    dueDate: new Date(Date.now() + 14 * 86400000).toISOString().slice(0, 10),
    blockerReason: null,
    note: "점검 예정",
    linkedType: null,
    linkedId: null,
    checkedAt: null,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "lri-10",
    templateId: "lct-11",
    phase: "pre_launch",
    area: "deployment",
    title: "배포/릴리즈 절차 placeholder",
    gateType: "must_have",
    status: "in_progress",
    priority: "critical",
    ownerAdminId: "admin1",
    ownerAdminNickname: "관리자",
    dueDate: null,
    blockerReason: null,
    note: "",
    linkedType: "deployment",
    linkedId: "rd-2",
    checkedAt: null,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "lri-11",
    templateId: "lct-7",
    phase: "pre_launch",
    area: "ads_business",
    title: "광고 신청·노출 검증",
    gateType: "should_have",
    status: "ready",
    priority: "medium",
    ownerAdminId: null,
    ownerAdminNickname: null,
    dueDate: null,
    blockerReason: null,
    note: "",
    linkedType: null,
    linkedId: null,
    checkedAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "lri-12",
    templateId: "lct-12",
    phase: "launch_day",
    area: "user_app",
    title: "채팅·알림 동작 검증",
    gateType: "should_have",
    status: "not_ready",
    priority: "medium",
    ownerAdminId: null,
    ownerAdminNickname: null,
    dueDate: null,
    blockerReason: null,
    note: "런칭 당일 체크",
    linkedType: null,
    linkedId: null,
    checkedAt: null,
    updatedAt: new Date().toISOString(),
  },
];

export function getLaunchReadinessItems(filters?: {
  phase?: LaunchReadinessPhase;
  area?: LaunchReadinessArea;
  status?: LaunchReadinessStatus;
}): LaunchReadinessItem[] {
  let list = [...ITEMS];
  if (filters?.phase) list = list.filter((i) => i.phase === filters.phase);
  if (filters?.area) list = list.filter((i) => i.area === filters.area);
  if (filters?.status) list = list.filter((i) => i.status === filters.status);
  return list.sort(
    (a, b) =>
      ["critical", "high", "medium", "low"].indexOf(a.priority) -
      ["critical", "high", "medium", "low"].indexOf(b.priority)
  );
}

export function getLaunchReadinessItemById(
  id: string
): LaunchReadinessItem | undefined {
  return ITEMS.find((i) => i.id === id);
}

export function getBlockedReadinessItems(): LaunchReadinessItem[] {
  return ITEMS.filter((i) => i.status === "blocked" && i.blockerReason);
}
