import {
  SAMPLE_MEMBER_DISPLAY,
  SAMPLE_MEMBER_USER_ID,
  SAMPLE_OWNER_DISPLAY,
  SAMPLE_OWNER_USER_ID,
} from "@/lib/mock-auth/mock-users";
import type { OrderChatMessage, OrderChatRoom } from "./types";

const STORE_ID = "mock-seoul-korean";
const STORE_NAME = "서울한식당";

function iso(d: string, t: string) {
  return `${d}T${t}`;
}

/** 샘플 주문방 5건 — 참여자: member qqqq / owner wwww (관리자는 열람만) */
export function buildInitialOrderChats(): { rooms: OrderChatRoom[]; messages: OrderChatMessage[] } {
  const rooms: OrderChatRoom[] = [];
  const messages: OrderChatMessage[] = [];

  const r1: OrderChatRoom = {
    id: "ocr-sh-1001",
    order_id: "sh-1001",
    order_no: "FD-20260321-1001",
    store_id: STORE_ID,
    store_name: STORE_NAME,
    buyer_user_id: SAMPLE_MEMBER_USER_ID,
    buyer_name: SAMPLE_MEMBER_DISPLAY,
    owner_user_id: SAMPLE_OWNER_USER_ID,
    owner_name: SAMPLE_OWNER_DISPLAY,
    room_status: "active",
    last_message: "맵기 덜 맵게 가능할까요?",
    last_message_at: iso("2026-03-21", "11:26:00.000Z"),
    unread_count_member: 0,
    unread_count_owner: 1,
    unread_count_admin: 0,
    last_chat_order_status: "pending",
    created_at: iso("2026-03-21", "11:25:00.000Z"),
    updated_at: iso("2026-03-21", "11:26:00.000Z"),
  };
  rooms.push(r1);
  messages.push(
    {
      id: "ocm-1001-1",
      room_id: r1.id,
      order_id: "sh-1001",
      sender_type: "system",
      sender_id: "system",
      sender_name: "시스템",
      message_type: "system",
      content: "주문이 접수되었어요",
      image_url: null,
      related_order_status: "pending",
      is_read_by_member: true,
      is_read_by_owner: false,
      is_read_by_admin: true,
      created_at: iso("2026-03-21", "11:25:01.000Z"),
    },
    {
      id: "ocm-1001-2",
      room_id: r1.id,
      order_id: "sh-1001",
      sender_type: "member",
      sender_id: SAMPLE_MEMBER_USER_ID,
      sender_name: SAMPLE_MEMBER_DISPLAY,
      message_type: "text",
      content: "맵기 덜 맵게 가능할까요?",
      image_url: null,
      related_order_status: null,
      is_read_by_member: true,
      is_read_by_owner: false,
      is_read_by_admin: true,
      created_at: iso("2026-03-21", "11:26:00.000Z"),
    }
  );

  const r2: OrderChatRoom = {
    id: "ocr-sh-1002",
    order_id: "sh-1002",
    order_no: "FD-20260321-1002",
    store_id: STORE_ID,
    store_name: STORE_NAME,
    buyer_user_id: SAMPLE_MEMBER_USER_ID,
    buyer_name: SAMPLE_MEMBER_DISPLAY,
    owner_user_id: SAMPLE_OWNER_USER_ID,
    owner_name: SAMPLE_OWNER_DISPLAY,
    room_status: "active",
    last_message: "네 같이 보내드릴게요",
    last_message_at: iso("2026-03-21", "11:05:00.000Z"),
    unread_count_member: 0,
    unread_count_owner: 0,
    unread_count_admin: 0,
    last_chat_order_status: "accepted",
    created_at: iso("2026-03-21", "11:00:00.000Z"),
    updated_at: iso("2026-03-21", "11:05:00.000Z"),
  };
  rooms.push(r2);
  messages.push(
    {
      id: "ocm-1002-1",
      room_id: r2.id,
      order_id: "sh-1002",
      sender_type: "system",
      sender_id: "system",
      sender_name: "시스템",
      message_type: "system",
      content: "주문이 접수되었어요",
      image_url: null,
      related_order_status: "pending",
      is_read_by_member: true,
      is_read_by_owner: true,
      is_read_by_admin: true,
      created_at: iso("2026-03-21", "11:00:01.000Z"),
    },
    {
      id: "ocm-1002-2",
      room_id: r2.id,
      order_id: "sh-1002",
      sender_type: "system",
      sender_id: "system",
      sender_name: "시스템",
      message_type: "system",
      content: "매장에서 주문을 확인했어요",
      image_url: null,
      related_order_status: "accepted",
      is_read_by_member: true,
      is_read_by_owner: true,
      is_read_by_admin: true,
      created_at: iso("2026-03-21", "11:01:00.000Z"),
    },
    {
      id: "ocm-1002-3",
      room_id: r2.id,
      order_id: "sh-1002",
      sender_type: "member",
      sender_id: SAMPLE_MEMBER_USER_ID,
      sender_name: SAMPLE_MEMBER_DISPLAY,
      message_type: "text",
      content: "젓가락 2개 부탁드려요",
      image_url: null,
      related_order_status: null,
      is_read_by_member: true,
      is_read_by_owner: true,
      is_read_by_admin: true,
      created_at: iso("2026-03-21", "11:03:00.000Z"),
    },
    {
      id: "ocm-1002-4",
      room_id: r2.id,
      order_id: "sh-1002",
      sender_type: "owner",
      sender_id: SAMPLE_OWNER_USER_ID,
      sender_name: SAMPLE_OWNER_DISPLAY,
      message_type: "text",
      content: "네 같이 보내드릴게요",
      image_url: null,
      related_order_status: null,
      is_read_by_member: true,
      is_read_by_owner: true,
      is_read_by_admin: true,
      created_at: iso("2026-03-21", "11:05:00.000Z"),
    }
  );

  const r3: OrderChatRoom = {
    id: "ocr-sh-1003",
    order_id: "sh-1003",
    order_no: "FD-20260321-1003",
    store_id: STORE_ID,
    store_name: STORE_NAME,
    buyer_user_id: SAMPLE_MEMBER_USER_ID,
    buyer_name: SAMPLE_MEMBER_DISPLAY,
    owner_user_id: SAMPLE_OWNER_USER_ID,
    owner_name: SAMPLE_OWNER_DISPLAY,
    room_status: "admin_review",
    last_message: "곧 출발합니다",
    last_message_at: iso("2026-03-21", "10:50:00.000Z"),
    unread_count_member: 0,
    unread_count_owner: 0,
    unread_count_admin: 1,
    last_chat_order_status: "preparing",
    created_at: iso("2026-03-21", "10:40:00.000Z"),
    updated_at: iso("2026-03-21", "10:50:00.000Z"),
  };
  rooms.push(r3);
  messages.push(
    {
      id: "ocm-1003-1",
      room_id: r3.id,
      order_id: "sh-1003",
      sender_type: "system",
      sender_id: "system",
      sender_name: "시스템",
      message_type: "system",
      content: "주문이 접수되었어요",
      image_url: null,
      related_order_status: "pending",
      is_read_by_member: true,
      is_read_by_owner: true,
      is_read_by_admin: true,
      created_at: iso("2026-03-21", "10:40:01.000Z"),
    },
    {
      id: "ocm-1003-2",
      room_id: r3.id,
      order_id: "sh-1003",
      sender_type: "system",
      sender_id: "system",
      sender_name: "시스템",
      message_type: "system",
      content: "매장에서 주문을 확인했어요",
      image_url: null,
      related_order_status: "accepted",
      is_read_by_member: true,
      is_read_by_owner: true,
      is_read_by_admin: true,
      created_at: iso("2026-03-21", "10:41:00.000Z"),
    },
    {
      id: "ocm-1003-3",
      room_id: r3.id,
      order_id: "sh-1003",
      sender_type: "system",
      sender_id: "system",
      sender_name: "시스템",
      message_type: "system",
      content: "음식을 준비하고 있어요",
      image_url: null,
      related_order_status: "preparing",
      is_read_by_member: true,
      is_read_by_owner: true,
      is_read_by_admin: true,
      created_at: iso("2026-03-21", "10:45:00.000Z"),
    },
    {
      id: "ocm-1003-4",
      room_id: r3.id,
      order_id: "sh-1003",
      sender_type: "member",
      sender_id: SAMPLE_MEMBER_USER_ID,
      sender_name: SAMPLE_MEMBER_DISPLAY,
      message_type: "text",
      content: "왜 아직 출발 안했나요?",
      image_url: null,
      related_order_status: null,
      is_read_by_member: true,
      is_read_by_owner: true,
      is_read_by_admin: false,
      created_at: iso("2026-03-21", "10:48:00.000Z"),
    },
    {
      id: "ocm-1003-5",
      room_id: r3.id,
      order_id: "sh-1003",
      sender_type: "owner",
      sender_id: SAMPLE_OWNER_USER_ID,
      sender_name: SAMPLE_OWNER_DISPLAY,
      message_type: "text",
      content: "곧 출발합니다",
      image_url: null,
      related_order_status: null,
      is_read_by_member: true,
      is_read_by_owner: true,
      is_read_by_admin: false,
      created_at: iso("2026-03-21", "10:50:00.000Z"),
    }
  );

  const r4: OrderChatRoom = {
    id: "ocr-sh-1004",
    order_id: "sh-1004",
    order_no: "FD-20260321-1004",
    store_id: STORE_ID,
    store_name: STORE_NAME,
    buyer_user_id: SAMPLE_MEMBER_USER_ID,
    buyer_name: SAMPLE_MEMBER_DISPLAY,
    owner_user_id: SAMPLE_OWNER_USER_ID,
    owner_name: SAMPLE_OWNER_DISPLAY,
    room_status: "active",
    last_message: "픽업할 수 있어요",
    last_message_at: iso("2026-03-21", "10:35:00.000Z"),
    unread_count_member: 0,
    unread_count_owner: 0,
    unread_count_admin: 0,
    last_chat_order_status: "ready_for_pickup",
    created_at: iso("2026-03-21", "10:15:00.000Z"),
    updated_at: iso("2026-03-21", "10:35:00.000Z"),
  };
  rooms.push(r4);
  messages.push(
    {
      id: "ocm-1004-1",
      room_id: r4.id,
      order_id: "sh-1004",
      sender_type: "system",
      sender_id: "system",
      sender_name: "시스템",
      message_type: "system",
      content: "주문이 접수되었어요",
      image_url: null,
      related_order_status: "pending",
      is_read_by_member: true,
      is_read_by_owner: true,
      is_read_by_admin: true,
      created_at: iso("2026-03-21", "10:15:01.000Z"),
    },
    {
      id: "ocm-1004-2",
      room_id: r4.id,
      order_id: "sh-1004",
      sender_type: "system",
      sender_id: "system",
      sender_name: "시스템",
      message_type: "system",
      content: "매장에서 주문을 확인했어요",
      image_url: null,
      related_order_status: "accepted",
      is_read_by_member: true,
      is_read_by_owner: true,
      is_read_by_admin: true,
      created_at: iso("2026-03-21", "10:16:00.000Z"),
    },
    {
      id: "ocm-1004-3",
      room_id: r4.id,
      order_id: "sh-1004",
      sender_type: "system",
      sender_id: "system",
      sender_name: "시스템",
      message_type: "system",
      content: "음식을 준비하고 있어요",
      image_url: null,
      related_order_status: "preparing",
      is_read_by_member: true,
      is_read_by_owner: true,
      is_read_by_admin: true,
      created_at: iso("2026-03-21", "10:25:00.000Z"),
    },
    {
      id: "ocm-1004-4",
      room_id: r4.id,
      order_id: "sh-1004",
      sender_type: "system",
      sender_id: "system",
      sender_name: "시스템",
      message_type: "system",
      content: "픽업할 수 있어요",
      image_url: null,
      related_order_status: "ready_for_pickup",
      is_read_by_member: true,
      is_read_by_owner: true,
      is_read_by_admin: true,
      created_at: iso("2026-03-21", "10:35:00.000Z"),
    }
  );

  const r5: OrderChatRoom = {
    id: "ocr-sh-1005",
    order_id: "sh-1005",
    order_no: "FD-20260321-1005",
    store_id: STORE_ID,
    store_name: STORE_NAME,
    buyer_user_id: SAMPLE_MEMBER_USER_ID,
    buyer_name: SAMPLE_MEMBER_DISPLAY,
    owner_user_id: SAMPLE_OWNER_USER_ID,
    owner_name: SAMPLE_OWNER_DISPLAY,
    room_status: "active",
    last_message: "주문이 완료되었어요",
    last_message_at: iso("2026-03-20", "18:40:00.000Z"),
    unread_count_member: 0,
    unread_count_owner: 0,
    unread_count_admin: 0,
    last_chat_order_status: "completed",
    created_at: iso("2026-03-20", "18:00:00.000Z"),
    updated_at: iso("2026-03-20", "18:40:00.000Z"),
  };
  rooms.push(r5);
  messages.push(
    {
      id: "ocm-1005-1",
      room_id: r5.id,
      order_id: "sh-1005",
      sender_type: "system",
      sender_id: "system",
      sender_name: "시스템",
      message_type: "system",
      content: "주문이 접수되었어요",
      image_url: null,
      related_order_status: "pending",
      is_read_by_member: true,
      is_read_by_owner: true,
      is_read_by_admin: true,
      created_at: iso("2026-03-20", "18:00:01.000Z"),
    },
    {
      id: "ocm-1005-2",
      room_id: r5.id,
      order_id: "sh-1005",
      sender_type: "system",
      sender_id: "system",
      sender_name: "시스템",
      message_type: "system",
      content: "매장에서 주문을 확인했어요",
      image_url: null,
      related_order_status: "accepted",
      is_read_by_member: true,
      is_read_by_owner: true,
      is_read_by_admin: true,
      created_at: iso("2026-03-20", "18:05:00.000Z"),
    },
    {
      id: "ocm-1005-3",
      room_id: r5.id,
      order_id: "sh-1005",
      sender_type: "system",
      sender_id: "system",
      sender_name: "시스템",
      message_type: "system",
      content: "음식을 준비하고 있어요",
      image_url: null,
      related_order_status: "preparing",
      is_read_by_member: true,
      is_read_by_owner: true,
      is_read_by_admin: true,
      created_at: iso("2026-03-20", "18:10:00.000Z"),
    },
    {
      id: "ocm-1005-4",
      room_id: r5.id,
      order_id: "sh-1005",
      sender_type: "system",
      sender_id: "system",
      sender_name: "시스템",
      message_type: "system",
      content: "배달이 출발했어요",
      image_url: null,
      related_order_status: "delivering",
      is_read_by_member: true,
      is_read_by_owner: true,
      is_read_by_admin: true,
      created_at: iso("2026-03-20", "18:22:00.000Z"),
    },
    {
      id: "ocm-1005-5",
      room_id: r5.id,
      order_id: "sh-1005",
      sender_type: "system",
      sender_id: "system",
      sender_name: "시스템",
      message_type: "system",
      content: "주문이 완료되었어요",
      image_url: null,
      related_order_status: "completed",
      is_read_by_member: true,
      is_read_by_owner: true,
      is_read_by_admin: true,
      created_at: iso("2026-03-20", "18:40:00.000Z"),
    }
  );

  return { rooms, messages };
}

export const INITIAL_ORDER_CHAT = buildInitialOrderChats();
