/**
 * dibaY 배달 메뉴판 전용 시각 토큰.
 * 배민·요기요 공식 디자인 가이드의 hex/간격 값이 아님 — 캡처 기반 보정 시 이 파일만 갱신한다.
 */
export const DibayMenuBoard = {
  pageBg: "var(--delivery-bg)",
  sectionBg: "#FFFFFF",
  brand: "var(--delivery-primary)",
  sectionGapPx: 8,
  cardRadiusPx: 4,
  productCardPadding: "16px",
  thumbSize: 92,
  title: { fontSizePx: 17, fontWeight: 700 },
  desc: { fontSizePx: 13, color: "var(--delivery-text-sub)" },
  price: { fontSizePx: 18, fontWeight: 800 },
  badgeRowMarginTopPx: 4,
  badgeGapPx: 4,
  badge: {
    ownerRecommended: {
      text: "사장님 추천",
      bg: "var(--delivery-badge-owner-bg)",
      fg: "var(--delivery-badge-owner-fg)",
      border: "0",
      radiusPx: 4,
      fontSizePx: 11,
      fontWeight: 700,
      padding: "0 6px",
      lineHeightPx: 20,
    },
    popular: {
      text: "인기",
      bg: "var(--delivery-badge-popular-bg)",
      fg: "var(--delivery-badge-popular-fg)",
      border: "0",
      radiusPx: 4,
      fontSizePx: 11,
      fontWeight: 700,
      padding: "0 6px",
    },
    representative: {
      text: "대표",
      bg: "var(--delivery-badge-primary-bg)",
      fg: "var(--delivery-badge-primary-fg)",
      border: "0",
      radiusPx: 4,
      fontSizePx: 11,
      fontWeight: 700,
      padding: "0 6px",
    },
    soldOut: {
      text: "품절",
      bg: "rgba(0,0,0,0.56)",
      fg: "#FFFFFF",
      radiusPx: 4,
      fontSizePx: 11,
      fontWeight: 700,
      padding: "4px 7px",
    },
    discount: {
      text: "할인",
      bg: "var(--delivery-badge-discount-bg)",
      fg: "var(--delivery-badge-discount-fg)",
      radiusPx: 4,
      fontSizePx: 11,
      fontWeight: 700,
      padding: "0 6px",
    },
  },
} as const;
