/**
 * dibaY 배달 메뉴판 전용 시각 토큰.
 * 배민·요기요 공식 디자인 가이드의 hex/간격 값이 아님 — 캡처 기반 보정 시 이 파일만 갱신한다.
 */
export const DibayMenuBoard = {
  pageBg: "#F6F7F8",
  sectionBg: "#FFFFFF",
  brand: "#1C8DB8",
  sectionGapPx: 8,
  cardRadiusPx: 4,
  productCardPadding: "14px 16px",
  thumbSize: 96,
  title: { fontSizePx: 15, fontWeight: 700 },
  desc: { fontSizePx: 12, color: "#777" },
  price: { fontSizePx: 14, fontWeight: 700 },
  badgeRowMarginTopPx: 5,
  badgeGapPx: 4,
  badge: {
    ownerRecommended: {
      text: "사장님 추천",
      bg: "#FFF4E5",
      fg: "#E46B00",
      border: "1px solid #FFD7A3",
      radiusPx: 4,
      fontSizePx: 10,
      fontWeight: 600,
      padding: "2px 5px",
      lineHeightPx: 14,
    },
    popular: {
      text: "인기",
      bg: "#FFF0F0",
      fg: "#E53935",
      border: "1px solid #FFCACA",
      radiusPx: 4,
      fontSizePx: 10,
      fontWeight: 600,
      padding: "2px 5px",
    },
    representative: {
      text: "대표",
      bg: "#EAF7FA",
      fg: "#1C8DB8",
      border: "1px solid #BEE7F0",
      radiusPx: 4,
      fontSizePx: 10,
      fontWeight: 600,
      padding: "2px 5px",
    },
    soldOut: {
      text: "품절",
      bg: "rgba(0,0,0,0.56)",
      fg: "#FFFFFF",
      radiusPx: 4,
      fontSizePx: 11,
      fontWeight: 700,
      padding: "4px 7px",
    },
    discount: {
      text: "할인",
      bg: "#FEEEEE",
      fg: "#E53935",
      radiusPx: 4,
      fontSizePx: 10,
      fontWeight: 700,
      padding: "2px 5px",
    },
  },
} as const;
