import type { LucideIcon } from "lucide-react";
import {
  AlarmClock,
  Award,
  BadgeCheck,
  BaggageClaim,
  Bell,
  Bookmark,
  Bot,
  Box,
  Briefcase,
  Building2,
  Calendar,
  Camera,
  Car,
  ChartBar,
  CircleUser,
  ClipboardList,
  Clock,
  Cloud,
  Coffee,
  Compass,
  CreditCard,
  Crown,
  FileText,
  Film,
  Flag,
  Flame,
  Gift,
  Globe,
  GraduationCap,
  Grid2x2,
  HandHeart,
  Headphones,
  Heart,
  HelpCircle,
  Home,
  Image,
  Inbox,
  Key,
  Landmark,
  LayoutGrid,
  LifeBuoy,
  Lightbulb,
  Link2,
  List,
  Map,
  MapPin,
  Megaphone,
  Menu,
  MessageCircle,
  Mic,
  Monitor,
  Moon,
  Music,
  Newspaper,
  Package,
  Palette,
  Phone,
  Pin,
  Plane,
  Play,
  Plus,
  Receipt,
  Rocket,
  Rss,
  Search,
  Settings,
  Share2,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Store,
  Sun,
  Tag,
  Target,
  Ticket,
  Trash2,
  TrendingUp,
  Truck,
  Umbrella,
  Upload,
  User,
  Users,
  Utensils,
  Video,
  Wallet,
  Wrench,
  Zap,
} from "lucide-react";

export type LucideBottomNavIconCategory =
  | "all"
  | "nav"
  | "commerce"
  | "communication"
  | "user"
  | "media"
  | "misc";

export type LucideBottomNavIconEntry = {
  name: string;
  category: Exclude<LucideBottomNavIconCategory, "all">;
};

/** Lucide(https://lucide.dev) 아이콘 — 관리자 선택·하단 탭 렌더 공통 allowlist */
export const LUCIDE_BOTTOM_NAV_ICON_CATALOG: LucideBottomNavIconEntry[] = [
  { name: "Home", category: "nav" },
  { name: "Compass", category: "nav" },
  { name: "Map", category: "nav" },
  { name: "MapPin", category: "nav" },
  { name: "Globe", category: "nav" },
  { name: "Menu", category: "nav" },
  { name: "LayoutGrid", category: "nav" },
  { name: "Grid2x2", category: "nav" },
  { name: "List", category: "nav" },
  { name: "Search", category: "nav" },
  { name: "Link2", category: "nav" },
  { name: "Pin", category: "nav" },
  { name: "Flag", category: "nav" },
  { name: "Target", category: "nav" },
  { name: "ShoppingBag", category: "commerce" },
  { name: "ShoppingCart", category: "commerce" },
  { name: "Store", category: "commerce" },
  { name: "Package", category: "commerce" },
  { name: "Box", category: "commerce" },
  { name: "Tag", category: "commerce" },
  { name: "Receipt", category: "commerce" },
  { name: "CreditCard", category: "commerce" },
  { name: "Wallet", category: "commerce" },
  { name: "Truck", category: "commerce" },
  { name: "BaggageClaim", category: "commerce" },
  { name: "Gift", category: "commerce" },
  { name: "Ticket", category: "commerce" },
  { name: "Briefcase", category: "commerce" },
  { name: "Building2", category: "commerce" },
  { name: "Landmark", category: "commerce" },
  { name: "Car", category: "commerce" },
  { name: "MessageCircle", category: "communication" },
  { name: "Inbox", category: "communication" },
  { name: "Phone", category: "communication" },
  { name: "Video", category: "communication" },
  { name: "Mic", category: "communication" },
  { name: "Bell", category: "communication" },
  { name: "Megaphone", category: "communication" },
  { name: "Headphones", category: "communication" },
  { name: "Bot", category: "communication" },
  { name: "Share2", category: "communication" },
  { name: "Rss", category: "communication" },
  { name: "User", category: "user" },
  { name: "Users", category: "user" },
  { name: "CircleUser", category: "user" },
  { name: "Settings", category: "user" },
  { name: "Shield", category: "user" },
  { name: "BadgeCheck", category: "user" },
  { name: "Key", category: "user" },
  { name: "GraduationCap", category: "user" },
  { name: "Crown", category: "user" },
  { name: "Award", category: "user" },
  { name: "HandHeart", category: "user" },
  { name: "LifeBuoy", category: "user" },
  { name: "HelpCircle", category: "user" },
  { name: "Heart", category: "media" },
  { name: "Star", category: "media" },
  { name: "Bookmark", category: "media" },
  { name: "Image", category: "media" },
  { name: "Camera", category: "media" },
  { name: "Film", category: "media" },
  { name: "Music", category: "media" },
  { name: "Play", category: "media" },
  { name: "Newspaper", category: "media" },
  { name: "FileText", category: "media" },
  { name: "Palette", category: "media" },
  { name: "Sparkles", category: "media" },
  { name: "Flame", category: "media" },
  { name: "Sun", category: "misc" },
  { name: "Moon", category: "misc" },
  { name: "Cloud", category: "misc" },
  { name: "Umbrella", category: "misc" },
  { name: "Coffee", category: "misc" },
  { name: "Utensils", category: "misc" },
  { name: "Calendar", category: "misc" },
  { name: "Clock", category: "misc" },
  { name: "AlarmClock", category: "misc" },
  { name: "ClipboardList", category: "misc" },
  { name: "ChartBar", category: "misc" },
  { name: "TrendingUp", category: "misc" },
  { name: "Zap", category: "misc" },
  { name: "Rocket", category: "misc" },
  { name: "Lightbulb", category: "misc" },
  { name: "Wrench", category: "misc" },
  { name: "Monitor", category: "misc" },
  { name: "Smartphone", category: "misc" },
  { name: "Upload", category: "misc" },
  { name: "Trash2", category: "misc" },
  { name: "Plus", category: "misc" },
  { name: "Plane", category: "misc" },
];

const LUCIDE_BOTTOM_NAV_ICON_COMPONENTS: Record<string, LucideIcon> = {
  AlarmClock,
  Award,
  BadgeCheck,
  BaggageClaim,
  Bell,
  Bookmark,
  Bot,
  Box,
  Briefcase,
  Building2,
  Calendar,
  Camera,
  Car,
  ChartBar,
  CircleUser,
  ClipboardList,
  Clock,
  Cloud,
  Coffee,
  Compass,
  CreditCard,
  Crown,
  FileText,
  Film,
  Flag,
  Flame,
  Gift,
  Globe,
  GraduationCap,
  Grid2x2,
  HandHeart,
  Headphones,
  Heart,
  HelpCircle,
  Home,
  Image,
  Inbox,
  Key,
  Landmark,
  LayoutGrid,
  LifeBuoy,
  Lightbulb,
  Link2,
  List,
  Map,
  MapPin,
  Megaphone,
  Menu,
  MessageCircle,
  Mic,
  Monitor,
  Moon,
  Music,
  Newspaper,
  Package,
  Palette,
  Phone,
  Pin,
  Plane,
  Play,
  Plus,
  Receipt,
  Rocket,
  Rss,
  Search,
  Settings,
  Share2,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Store,
  Sun,
  Tag,
  Target,
  Ticket,
  Trash2,
  TrendingUp,
  Truck,
  Umbrella,
  Upload,
  User,
  Users,
  Utensils,
  Video,
  Wallet,
  Wrench,
  Zap,
};

const LUCIDE_ICON_NAME_SET = new Set(LUCIDE_BOTTOM_NAV_ICON_CATALOG.map((entry) => entry.name));

export function isLucideBottomNavIconName(value: unknown): value is string {
  return typeof value === "string" && LUCIDE_ICON_NAME_SET.has(value);
}

export function resolveLucideBottomNavIcon(name: string): LucideIcon | null {
  return LUCIDE_BOTTOM_NAV_ICON_COMPONENTS[name] ?? null;
}

export function filterLucideBottomNavIcons(
  query: string,
  category: LucideBottomNavIconCategory = "all"
): LucideBottomNavIconEntry[] {
  const q = query.trim().toLowerCase();
  return LUCIDE_BOTTOM_NAV_ICON_CATALOG.filter((entry) => {
    if (category !== "all" && entry.category !== category) return false;
    if (!q) return true;
    return entry.name.toLowerCase().includes(q);
  });
}

export const LUCIDE_BOTTOM_NAV_ICON_LIBRARY_URL = "https://lucide.dev/icons";
