/** @deprecated import from `@/lib/ui/i18n-compact-label-classes` — 배달 browse 전용 alias */
export {
  I18N_COMPACT_TABLIST_SCROLL as STORE_BROWSE_PRIMARY_TABLIST,
  I18N_COMPACT_TAB_BUTTON as STORE_BROWSE_PRIMARY_TAB_BUTTON,
  I18N_COMPACT_TAB_ICON as STORE_BROWSE_PRIMARY_TAB_ICON,
  I18N_COMPACT_TAB_LABEL as STORE_BROWSE_PRIMARY_TAB_LABEL,
  I18N_COMPACT_TAB_BUTTON as STORE_BROWSE_SUB_CHIP_BUTTON,
  I18N_COMPACT_CHIP_LABEL as STORE_BROWSE_SUB_CHIP_LABEL,
  I18N_COMPACT_SUB_CARD as STORE_BROWSE_SUB_CARD,
  I18N_COMPACT_SUB_CARD_ICON_WRAP as STORE_BROWSE_SUB_CARD_ICON_WRAP,
  I18N_COMPACT_SUB_CARD_ICON as STORE_BROWSE_SUB_CARD_ICON,
  I18N_COMPACT_SUB_CARD_LABEL as STORE_BROWSE_SUB_CARD_LABEL,
  I18N_COMPACT_SECTION_TITLE as STORE_BROWSE_SECTION_TITLE,
} from "@/lib/ui/i18n-compact-label-classes";
