/**
 * C1 — Default HOME composition policy = CURRENT PRODUCTION BEHAVIOR (declarative only).
 *
 * Does not wire into `composeStoresHomeFeed` — runtime unchanged until C3+ engine cutover.
 * Caps must stay in sync with `lib/stores/stores-home-composer.ts` constants.
 */

import type { StoresCompositionSectionContract } from "@/lib/stores/composition/stores-composition-contract";
import {
  STORES_HOME_CAMPAIGN_SHELF_MAX,
  STORES_HOME_NEARBY_MAX,
  STORES_HOME_NEW_STORE_SHELF_MAX,
  STORES_HOME_POPULAR_SHELF_MAX,
  STORES_HOME_SLOT0_FOOD_MAX,
  STORES_HOME_SLOT5_FOOD_MAX,
  STORES_HOME_TOP_RATED_SHELF_MAX,
} from "@/lib/stores/stores-home-composer";

const NOT_CONSUMED_INTERVAL = { consumed: false as const, reason: "NOT_CONSUMED" as const };

/**
 * Frozen @ C1 / CUT 2 — mirrors `composeStoresHomeFeed` + Hub presentation order.
 * `slot1Stores` / `slot6NearbyStores` disabled (main_stores removed; fast_arrival deferred).
 * Remainder discoverability → `slot6RestStores` (rest_stores).
 */
export const STORES_HOME_COMPOSITION_DEFAULT_POLICY: readonly StoresCompositionSectionContract[] = [
  {
    surface: "home",
    slot: "slot0Food",
    contentType: "food_product",
    enabled: true,
    order: 0,
    interval: NOT_CONSUMED_INTERVAL,
    max: STORES_HOME_SLOT0_FOOD_MAX,
    titleAuthority: "presentation_i18n",
    titleRef: "store_order_now_title",
    notes: "Open+deliverable filter in composer; owner_representative product per store.",
  },
  {
    surface: "home",
    slot: "slot1Stores",
    contentType: "store",
    enabled: false,
    order: 1,
    interval: NOT_CONSUMED_INTERVAL,
    max: null,
    titleAuthority: "none",
    notes: "CUT 2 REMOVED — main_stores; always empty composition; rest_stores owns remainder.",
  },
  {
    surface: "home",
    slot: "slot2Food",
    contentType: "food_product",
    enabled: true,
    order: 2,
    interval: NOT_CONSUMED_INTERVAL,
    max: STORES_HOME_POPULAR_SHELF_MAX,
    titleAuthority: "presentation_i18n",
    titleRef: "store_home_popular_stores_title",
    notes: "popular_menu — Popular metric shelf; platform_popular when qualified.",
  },
  {
    surface: "home",
    slot: "newStoreFood",
    contentType: "food_product",
    enabled: true,
    order: 3,
    interval: NOT_CONSUMED_INTERVAL,
    max: STORES_HOME_NEW_STORE_SHELF_MAX,
    titleAuthority: "presentation_i18n",
    titleRef: "store_home_new_stores_title",
    notes: "first_listed_at DESC within new-store signal; not Discovery home ranking.",
  },
  {
    surface: "home",
    slot: "campaignFood",
    contentType: "campaign_food",
    enabled: true,
    order: 4,
    interval: NOT_CONSUMED_INTERVAL,
    max: STORES_HOME_CAMPAIGN_SHELF_MAX,
    titleAuthority: "presentation_i18n",
    titleRef: "store_home_campaigns_title",
    notes: "editorial_promo — store.discoveryCampaign from home-feed; eligibility NOT editable here.",
  },
  {
    surface: "home",
    slot: "slot3Food",
    contentType: "food_product",
    enabled: true,
    order: 5,
    interval: NOT_CONSUMED_INTERVAL,
    max: STORES_HOME_POPULAR_SHELF_MAX,
    titleAuthority: "presentation_i18n",
    titleRef: "store_badge_menu_discount",
    notes: "delivery_fee_benefit — delivery_fee_strike evidence filter.",
  },
  {
    surface: "home",
    slot: "slot4Food",
    contentType: "food_product",
    enabled: true,
    order: 6,
    interval: NOT_CONSUMED_INTERVAL,
    max: STORES_HOME_TOP_RATED_SHELF_MAX,
    titleAuthority: "presentation_i18n",
    titleRef: "store_spot_recommended_subtitle",
    notes: "rating≥4 & reviews≥3 filter.",
  },
  {
    surface: "home",
    slot: "slot5Food",
    contentType: "food_product",
    enabled: true,
    order: 7,
    interval: NOT_CONSUMED_INTERVAL,
    max: STORES_HOME_SLOT5_FOOD_MAX,
    titleAuthority: "presentation_i18n",
    titleRef: "store_spot_recommended_title",
    notes: "recommended — stores.is_featured; Hub grid slice(0,4) presentation cap.",
  },
  {
    surface: "home",
    slot: "slot6NearbyStores",
    contentType: "store",
    enabled: false,
    order: 8,
    interval: NOT_CONSUMED_INTERVAL,
    max: STORES_HOME_NEARBY_MAX,
    titleAuthority: "presentation_i18n",
    titleRef: "store_neighborhood_more_title",
    notes: "CUT 2 DEFERRED fast_arrival — not TARGET v1 core section.",
  },
  {
    surface: "home",
    slot: "slot6RestStores",
    contentType: "store",
    enabled: true,
    order: 9,
    interval: NOT_CONSUMED_INTERVAL,
    max: null,
    titleAuthority: "presentation_i18n",
    titleRef: "store_feed_stores_title",
    notes: "rest_stores — discovery pool remainder after slot0 + horizontal deprioritize.",
  },
  {
    surface: "home",
    slot: "homePaidAdInsertion",
    contentType: "ad",
    enabled: false,
    order: 10,
    interval: NOT_CONSUMED_INTERVAL,
    max: 5,
    titleAuthority: "campaign_field_copy",
    notes: "Stores A — paid ad rail; enable via Admin composition policy. CUT 4 surface = rest_stores.",
  },
  {
    surface: "home",
    slot: "homeCouponInsertion",
    contentType: "coupon",
    enabled: false,
    order: 11,
    interval: NOT_CONSUMED_INTERVAL,
    max: 5,
    titleAuthority: "campaign_field_copy",
    notes: "Stores A — coupon rail; enable via Admin composition policy. CUT 6.",
  },
] as const;
