/** 메신저 배달 주문 — 우측 주문 상세 peek 패널 (채팅 본문 25% 노출) */
export const STORE_ORDER_DELIVERY_DETAIL_DRAWER_MS = 270;

export const STORE_ORDER_DELIVERY_DETAIL_DRAWER_WIDTH_CLASS = "w-[75vw] max-w-[75vw]";

export const STORE_ORDER_DELIVERY_DETAIL_DRAWER_TRANSITION_MS_CLASS = "duration-[270ms]";

export const STORE_ORDER_DELIVERY_DETAIL_DRAWER_TRANSFORM_CLASS = `transition-transform ease-out ${STORE_ORDER_DELIVERY_DETAIL_DRAWER_TRANSITION_MS_CLASS}`;

export const STORE_ORDER_DELIVERY_DETAIL_DRAWER_BACKDROP_TRANSITION_CLASS = `transition-opacity ease-out ${STORE_ORDER_DELIVERY_DETAIL_DRAWER_TRANSITION_MS_CLASS}`;
