import type { AdminDeliveryOrder, OrderReport, OrderStatusLog } from "./types";

const iso = (d: string) => `${d}T10:30:00.000Z`;

export const INITIAL_DELIVERY_ORDERS: AdminDeliveryOrder[] = [
  {
    id: "fd-1",
    orderNo: "FD-20260321-0001",
    buyerUserId: "u-bk",
    buyerName: "BK",
    buyerPhone: "+63-900-111-0001",
    storeId: "mock-seoul-korean",
    storeName: "서울한식당",
    storeSlug: "seoul-korean-house",
    storeOwnerUserId: "owner-seoul",
    storeOwnerName: "김사장(샘플)",
    orderType: "delivery",
    addressSummary: "Manila · Malate",
    addressDetail: "샘플 동 101호",
    requestNote: "수저 2세트",
    items: [
      {
        id: "li-1a",
        menuName: "김치찌개",
        options: [
          { optionGroupName: "맵기", optionName: "보통맛", optionPrice: 0 },
          { optionGroupName: "추가", optionName: "공기밥추가", optionPrice: 30 },
        ],
        qty: 1,
        unitPrice: 250,
        optionExtra: 30,
        lineTotal: 280,
      },
    ],
    productAmount: 250,
    optionAmount: 30,
    deliveryFee: 50,
    discountAmount: 0,
    finalAmount: 330,
    paymentStatus: "paid",
    orderStatus: "pending",
    settlementStatus: "scheduled",
    adminActionStatus: "none",
    adminMemo: "",
    hasReport: false,
    createdAt: iso("2026-03-21"),
    updatedAt: iso("2026-03-21"),
    settlement: {
      id: "st-1",
      grossAmount: 330,
      feeAmount: 33,
      settlementAmount: 297,
      settlementStatus: "scheduled",
      scheduledDate: "2026-03-28",
    },
  },
  {
    id: "fd-2",
    orderNo: "FD-20260321-0002",
    buyerUserId: "u-02",
    buyerName: "user02",
    buyerPhone: "+63-900-222-0002",
    storeId: "mock-hk-style",
    storeName: "홍콩반점 스타일 하우스",
    storeSlug: "hk-style-house",
    storeOwnerUserId: "owner-hk",
    storeOwnerName: "왕사장(샘플)",
    orderType: "delivery",
    addressSummary: "Angeles",
    requestNote: "덜 맵게",
    items: [
      {
        id: "li-2a",
        menuName: "짜장면",
        options: [
          { optionGroupName: "곱빼기", optionName: "곱빼기", optionPrice: 40 },
          { optionGroupName: "추가메뉴", optionName: "군만두 5개", optionPrice: 80 },
        ],
        qty: 1,
        unitPrice: 180,
        optionExtra: 120,
        lineTotal: 300,
      },
    ],
    productAmount: 180,
    optionAmount: 120,
    deliveryFee: 0,
    discountAmount: 0,
    finalAmount: 300,
    paymentStatus: "paid",
    orderStatus: "preparing",
    settlementStatus: "scheduled",
    adminActionStatus: "none",
    adminMemo: "",
    hasReport: false,
    createdAt: iso("2026-03-21"),
    updatedAt: iso("2026-03-21"),
    cancelRequest: {
      reason: "주문 실수로 잘못 눌렀습니다.",
      requestedAt: iso("2026-03-21"),
      status: "pending",
    },
    settlement: {
      id: "st-2",
      grossAmount: 300,
      feeAmount: 30,
      settlementAmount: 270,
      settlementStatus: "scheduled",
      scheduledDate: "2026-03-28",
    },
  },
  {
    id: "fd-3",
    orderNo: "FD-20260321-0003",
    buyerUserId: "u-03",
    buyerName: "user03",
    buyerPhone: "+63-900-333-0003",
    storeId: "mock-korea-snackbar",
    storeName: "코리아 스낵바",
    storeSlug: "korea-snackbar",
    storeOwnerUserId: "owner-snack",
    storeOwnerName: "박사장(샘플)",
    orderType: "pickup",
    pickupNote: "30분 후 픽업",
    requestNote: "",
    items: [
      {
        id: "li-3a",
        menuName: "치즈떡볶이",
        options: [{ optionGroupName: "맵기", optionName: "보통맛", optionPrice: 0 }],
        qty: 2,
        unitPrice: 190,
        optionExtra: 0,
        lineTotal: 380,
      },
    ],
    productAmount: 380,
    optionAmount: 0,
    deliveryFee: 0,
    discountAmount: 0,
    finalAmount: 380,
    paymentStatus: "paid",
    orderStatus: "ready_for_pickup",
    settlementStatus: "scheduled",
    adminActionStatus: "none",
    adminMemo: "",
    hasReport: false,
    createdAt: iso("2026-03-21"),
    updatedAt: iso("2026-03-21"),
    settlement: {
      id: "st-3",
      grossAmount: 380,
      feeAmount: 38,
      settlementAmount: 342,
      settlementStatus: "scheduled",
      scheduledDate: "2026-03-28",
    },
  },
  {
    id: "fd-4",
    orderNo: "FD-20260321-0004",
    buyerUserId: "u-04",
    buyerName: "user04",
    buyerPhone: "+63-900-444-0004",
    storeId: "mock-pasta-grill",
    storeName: "Pasta & Grill House",
    storeSlug: "pasta-grill-house",
    storeOwnerUserId: "owner-pasta",
    storeOwnerName: "John(샘플)",
    orderType: "delivery",
    addressSummary: "BGC",
    items: [
      {
        id: "li-4a",
        menuName: "까보나라",
        options: [{ optionGroupName: "사이즈", optionName: "레귤러", optionPrice: 0 }],
        qty: 1,
        unitPrice: 290,
        optionExtra: 0,
        lineTotal: 290,
      },
      {
        id: "li-4b",
        menuName: "시저샐러드",
        options: [],
        qty: 1,
        unitPrice: 240,
        optionExtra: 0,
        lineTotal: 240,
      },
    ],
    productAmount: 530,
    optionAmount: 0,
    deliveryFee: 80,
    discountAmount: 0,
    finalAmount: 610,
    paymentStatus: "refunded",
    orderStatus: "refunded",
    settlementStatus: "cancelled",
    adminActionStatus: "refund_approved",
    refundReason: "매장 재고 없음",
    adminMemo: "고객 통보 완료 (시뮬)",
    hasReport: false,
    createdAt: iso("2026-03-20"),
    updatedAt: iso("2026-03-21"),
    refundRequest: {
      reason: "매장 재고 없음",
      category: "재고 없음",
      requestedBy: "store",
      requestedAt: iso("2026-03-20"),
      status: "approved",
    },
    settlement: {
      id: "st-4",
      grossAmount: 610,
      feeAmount: 61,
      settlementAmount: 549,
      settlementStatus: "cancelled",
    },
  },
  {
    id: "fd-5",
    orderNo: "FD-20260321-0005",
    buyerUserId: "u-05",
    buyerName: "user05",
    buyerPhone: "+63-900-555-0005",
    storeId: "mock-seoul-korean",
    storeName: "서울한식당",
    storeSlug: "seoul-korean-house",
    storeOwnerUserId: "owner-seoul",
    storeOwnerName: "김사장(샘플)",
    orderType: "delivery",
    addressSummary: "Quezon City",
    items: [
      {
        id: "li-5a",
        menuName: "불고기정식",
        options: [],
        qty: 1,
        unitPrice: 320,
        optionExtra: 0,
        lineTotal: 320,
      },
    ],
    productAmount: 320,
    optionAmount: 0,
    deliveryFee: 50,
    discountAmount: 0,
    finalAmount: 370,
    paymentStatus: "paid",
    orderStatus: "completed",
    settlementStatus: "held",
    adminActionStatus: "dispute_reviewing",
    adminMemo: "고객 응대 중",
    hasReport: true,
    disputeMemo: "고객 분쟁 신고 접수",
    createdAt: iso("2026-03-19"),
    updatedAt: iso("2026-03-21"),
    settlement: {
      id: "st-5",
      grossAmount: 370,
      feeAmount: 37,
      settlementAmount: 333,
      settlementStatus: "held",
      holdReason: "고객 분쟁 신고 접수",
    },
  },
  {
    id: "fd-6",
    orderNo: "FD-20260321-0006",
    buyerUserId: "u-06",
    buyerName: "user06",
    buyerPhone: "+63-900-666-0006",
    storeId: "mock-hk-style",
    storeName: "홍콩반점 스타일 하우스",
    storeSlug: "hk-style-house",
    storeOwnerUserId: "owner-hk",
    storeOwnerName: "왕사장(샘플)",
    orderType: "delivery",
    addressSummary: "Makati",
    items: [
      {
        id: "li-6a",
        menuName: "짬뽕",
        options: [{ optionGroupName: "맵기", optionName: "매운맛", optionPrice: 0 }],
        qty: 1,
        unitPrice: 220,
        optionExtra: 0,
        lineTotal: 220,
      },
    ],
    productAmount: 220,
    optionAmount: 0,
    deliveryFee: 60,
    discountAmount: 0,
    finalAmount: 280,
    paymentStatus: "paid",
    orderStatus: "refund_requested",
    settlementStatus: "held",
    adminActionStatus: "none",
    adminMemo: "",
    hasReport: false,
    createdAt: iso("2026-03-21"),
    updatedAt: iso("2026-03-21"),
    refundRequest: {
      reason: "배달 지연 1시간 초과",
      category: "배달 지연",
      requestedBy: "buyer",
      requestedAt: iso("2026-03-21"),
      status: "pending",
    },
    settlement: {
      id: "st-6",
      grossAmount: 280,
      feeAmount: 28,
      settlementAmount: 252,
      settlementStatus: "held",
      holdReason: "환불 요청 검토",
    },
  },
];

function seedLog(
  id: string,
  orderId: string,
  action: string,
  from: OrderStatusLog["toOrderStatus"],
  to: OrderStatusLog["toOrderStatus"],
  reason?: string
): OrderStatusLog {
  return {
    id,
    orderId,
    actorType: "system",
    actorId: "system",
    action,
    fromOrderStatus: from,
    toOrderStatus: to,
    reason,
    createdAt: iso("2026-03-21"),
  };
}

export const INITIAL_ORDER_LOGS: OrderStatusLog[] = [
  seedLog("log-1", "fd-1", "주문 생성", undefined, "pending"),
  seedLog("log-2", "fd-2", "결제 완료", "pending", "accepted"),
  seedLog("log-3", "fd-2", "조리 시작", "accepted", "preparing"),
  seedLog("log-4", "fd-3", "픽업 준비 완료", "preparing", "ready_for_pickup"),
  seedLog("log-5", "fd-4", "환불 승인", "refund_requested", "refunded", "매장 재고 없음"),
  seedLog("log-6", "fd-5", "배달 완료", "delivering", "completed"),
  seedLog("log-7", "fd-5", "정산 보류", undefined, undefined, "분쟁 접수"),
  seedLog("log-8", "fd-6", "환불 요청 접수", "preparing", "refund_requested"),
];

export const INITIAL_ORDER_REPORTS: OrderReport[] = [
  {
    id: "rep-1",
    orderId: "fd-5",
    reporterUserId: "u-05",
    reporterName: "user05",
    reportType: "응대 문제",
    content: "매장 응대가 불친절했습니다 (시뮬)",
    status: "reviewing",
    adminResult: "검토중 — 매장에 사실 확인 요청",
    createdAt: iso("2026-03-20"),
  },
];
