import { stopCallHeartbeatWatchdog } from "@/lib/call/native/call-heartbeat-watchdog";
import { stopCallV4CallerActivePoll } from "@/lib/community-messenger/call-v4/call-v4-caller-active";
import { stopCallV4ConnectedTerminalWatch } from "@/lib/community-messenger/call-v4/call-v4-connected-terminal-watch";
import { clearCallV4ConnectionWarm } from "@/lib/community-messenger/call-v4/call-v4-connection-warm";
import { releaseCallV4AudioRoute } from "@/lib/community-messenger/call-v4/call-v4-audio-route";
import { clearCallV4WebCallScreenReady } from "@/lib/community-messenger/call-v4/call-v4-exit-guard";
import { logCallV4 } from "@/lib/community-messenger/call-v4/call-v4-debug";
import { clearCallV4NativeAcceptingSurface, clearCallV4NativeIncomingSurface, clearCallV4SurfaceOwner } from "@/lib/community-messenger/call-v4/call-v4-incoming-surface";
import { clearNativeAcceptInflight } from "@/lib/community-messenger/call-v4/call-v4-native-accept-flight";
import { syncCallV4NativeTerminalCleanup } from "@/lib/community-messenger/call-v4/call-v4-native-lifecycle";
import { useCallV4MediaStore } from "@/lib/community-messenger/call-v4/call-v4-media-state";
import { stopCallV4NativeActiveSession } from "@/lib/community-messenger/call-v4/call-v4-native-active-session";
import { resetCallV4AcceptPatchStateForCallId } from "@/lib/community-messenger/call-v4/call-v4-patch-guard";
import { forceResetCommunityMessengerCallRuntimeSurface } from "@/lib/community-messenger/call-runtime-registry";
import { useCallV4Store } from "@/lib/community-messenger/call-v4/call-v4-store";
import type { CallV4TerminalPhase } from "@/lib/community-messenger/call-v4/call-v4-types";

export async function cleanupCallV4(callId: string, reason: CallV4TerminalPhase | string): Promise<void> {
  const sid = callId.trim();
  logCallV4("cleanup_start", { callId: sid, reason });
  clearCallV4WebCallScreenReady(sid);
  stopCallHeartbeatWatchdog(sid);
  logCallV4("call_heartbeat_watchdog_stop", { callId: sid, reason });
  stopCallV4CallerActivePoll();
  stopCallV4ConnectedTerminalWatch(sid);
  const { leaveCallV4Agora } = await import("@/lib/community-messenger/call-v4/call-v4-agora");
  await leaveCallV4Agora(sid);
  await releaseCallV4AudioRoute(sid, "v4_cleanup");
  clearCallV4ConnectionWarm(sid);
  resetCallV4AcceptPatchStateForCallId(sid);
  clearCallV4NativeAcceptingSurface(sid);
  clearNativeAcceptInflight(sid, String(reason));
  syncCallV4NativeTerminalCleanup(sid, reason);
  clearCallV4NativeIncomingSurface(sid, "cleanup");
  clearCallV4SurfaceOwner(sid, "cleanup");
  useCallV4MediaStore.getState().reset();
  forceResetCommunityMessengerCallRuntimeSurface();
  await stopCallV4NativeActiveSession(sid, String(reason));
  useCallV4Store.getState().resetToIdle();
  logCallV4("cleanup_done", { callId: sid, reason });
}
