-- Optional phase-2: owner_store_commerce unread count without 2500-row scan
-- Apply only if notification_type=commerce pre-filter + idx_notifications_user_unread_created
-- still exceeds 200ms target.

-- create or replace function public.count_owner_store_commerce_unread(p_user_id uuid)
-- returns bigint
-- language sql
-- stable
-- security invoker
-- set search_path = public
-- as $$
--   select count(*)::bigint
--   from public.notifications n
--   where n.user_id = p_user_id
--     and n.is_read = false
--     and n.notification_type = 'commerce'
--     and (n.meta->>'kind') in (
--       'store_order_created',
--       'store_order_payment_completed',
--       'store_order_buyer_cancelled',
--       'store_order_refund_requested'
--     );
-- $$;
