import { POST_LOGIN_PATH } from "@/lib/auth/post-login-path";
import { buildProfileSetupHref } from "@/lib/auth/profile-setup-flow";
import { isAutoGeneratedDibayId } from "@/lib/auth/dibay-id-policy";
import { hasStoreTermsConsent } from "@/lib/auth/store-member-policy";
import {
  sanitizeFreshLoginLandingPath,
  sanitizeNextPath,
  withNextSearchParam,
} from "@/lib/auth/safe-next-path";
import { isPrivilegedAdminRole } from "@/lib/auth/admin-policy";

export type DibayOnboardingStatusValue =
  | "pending"
  | "oauth_authenticated"
  | "terms_required"
  | "id_required"
  | "profile_ready"
  | "completed";

/**
 * DIBAY 가입 phase — SNS OAuth 직후 Supabase session ≠ signupComplete.
 * mutation API 는 requireSignupCompleteForUser 로 403.
 * @see docs/auth-account-linking-policy.md
 */
export type DibaySignupPhase =
  | "pending_auth"
  | "oauth_authenticated"
  | "terms_required"
  | "id_required"
  | "profile_ready"
  | "completed";

export type DibaySignupProfileInput = {
  id?: string | null;
  dibay_id?: string | null;
  dibay_id_locked?: boolean | null;
  username?: string | null;
  username_confirmed?: boolean | null;
  display_name?: string | null;
  avatar_url?: string | null;
  terms_accepted_at?: string | null;
  terms_version?: string | null;
  privacy_accepted_at?: string | null;
  privacy_version?: string | null;
  onboarding_completed_at?: string | null;
  onboarding_status?: string | null;
  role?: string | null;
};

export type DibaySignupStatus = {
  phase: DibaySignupPhase;
  consentComplete: boolean;
  dibayIdComplete: boolean;
  profileComplete: boolean;
  legacyCompleted: boolean;
  signupComplete: boolean;
  onboardingStatus: DibayOnboardingStatusValue;
};

function pickTrimmed(input: unknown): string | null {
  if (typeof input !== "string") return null;
  const trimmed = input.trim();
  return trimmed.length > 0 ? trimmed : null;
}

export function isDibayIdComplete(profile: DibaySignupProfileInput | null | undefined): boolean {
  if (!profile) return false;
  const locked = profile.dibay_id_locked === true;
  const dibayId = pickTrimmed(profile.dibay_id) ?? pickTrimmed(profile.username);
  if (!locked || !dibayId) return false;
  if (isAutoGeneratedDibayId(dibayId)) return false;
  if (profile.username_confirmed === false) return false;
  return true;
}

export function isDibayProfileComplete(profile: DibaySignupProfileInput | null | undefined): boolean {
  if (!profile) return false;
  const displayName = pickTrimmed(profile.display_name);
  const avatarUrl = pickTrimmed(profile.avatar_url);
  return Boolean(displayName && avatarUrl);
}

export function deriveDibaySignupStatus(
  profile: DibaySignupProfileInput | null | undefined,
  opts?: { hasSession?: boolean }
): DibaySignupStatus {
  const hasSession = opts?.hasSession !== false;
  if (!hasSession || !profile?.id) {
    return {
      phase: "pending_auth",
      consentComplete: false,
      dibayIdComplete: false,
      profileComplete: false,
      legacyCompleted: false,
      signupComplete: false,
      onboardingStatus: "pending",
    };
  }

  if (isPrivilegedAdminRole(profile.role ?? null)) {
    return {
      phase: "completed",
      consentComplete: true,
      dibayIdComplete: true,
      profileComplete: true,
      legacyCompleted: true,
      signupComplete: true,
      onboardingStatus: "completed",
    };
  }

  const consentComplete = hasStoreTermsConsent({
    terms_accepted_at: profile.terms_accepted_at ?? null,
    terms_version: profile.terms_version ?? null,
    privacy_accepted_at: profile.privacy_accepted_at ?? null,
    privacy_version: profile.privacy_version ?? null,
  });
  const dibayIdComplete = isDibayIdComplete(profile);
  const profileComplete = isDibayProfileComplete(profile);
  const legacyCompleted = Boolean(profile.onboarding_completed_at);
  const signupComplete = consentComplete && dibayIdComplete && profileComplete;

  let phase: DibaySignupPhase;
  if (signupComplete) {
    phase = "completed";
  } else if (!consentComplete) {
    phase = "terms_required";
  } else if (!dibayIdComplete) {
    phase = "id_required";
  } else {
    phase = "profile_ready";
  }

  let onboardingStatus: DibayOnboardingStatusValue = "oauth_authenticated";
  const raw = pickTrimmed(profile.onboarding_status);
  if (raw === "pending" || raw === "oauth_authenticated" || raw === "terms_required" || raw === "id_required" || raw === "profile_ready" || raw === "completed") {
    onboardingStatus = raw;
  } else if (signupComplete) {
    onboardingStatus = "completed";
  } else if (!consentComplete) {
    onboardingStatus = "terms_required";
  } else if (!dibayIdComplete) {
    onboardingStatus = "id_required";
  }

  return {
    phase,
    consentComplete,
    dibayIdComplete,
    profileComplete,
    legacyCompleted,
    signupComplete,
    onboardingStatus,
  };
}

export function isDibaySignupComplete(status: DibaySignupStatus): boolean {
  return status.signupComplete || status.phase === "completed";
}

export const DIBAY_SIGNUP_TERMS_PATH = "/auth/onboarding/terms";
export const DIBAY_SIGNUP_DIBAY_ID_PATH = "/auth/onboarding/dibay-id";

export function isDibaySignupGateExcludedPath(pathname: string): boolean {
  const p = (pathname ?? "").split("?")[0]?.trim() || "";
  return (
    p === "/login" ||
    p.startsWith("/login/") ||
    p === "/signup" ||
    p.startsWith("/signup/") ||
    p.startsWith("/auth/onboarding/") ||
    p === "/auth/consent" ||
    p.startsWith("/auth/consent") ||
    p.startsWith("/auth/callback") ||
    p === "/onboarding/username" ||
    p.startsWith("/onboarding/username/") ||
    p.startsWith("/terms") ||
    p.startsWith("/privacy") ||
    p.startsWith("/account/delete-request")
  );
}

export function resolveDibaySignupRoute(
  status: DibaySignupStatus,
  next?: string | null
): string {
  const safeNext = sanitizeNextPath(next ?? null);

  if (status.phase === "completed" || status.signupComplete) {
    return sanitizeFreshLoginLandingPath(safeNext) ?? POST_LOGIN_PATH;
  }
  if (!status.consentComplete || status.phase === "terms_required") {
    return withNextSearchParam(DIBAY_SIGNUP_TERMS_PATH, safeNext);
  }
  if (!status.dibayIdComplete || status.phase === "id_required") {
    return withNextSearchParam(DIBAY_SIGNUP_DIBAY_ID_PATH, safeNext);
  }
  if (!status.profileComplete || status.phase === "profile_ready") {
    return buildProfileSetupHref({ next: safeNext });
  }
  return sanitizeFreshLoginLandingPath(safeNext) ?? POST_LOGIN_PATH;
}
