/**
 * DIBAY @public-id SSOT — 카톡·텔레그램식 단일 정의
 *
 * CONTRACT
 * - UI·gate·검색·메신저 subtitle 은 이 파일만 해석한다.
 * - `dibay_id` / `username` / `username_confirmed` / `dibay_id_locked` 를 화면마다 따로 조합하지 않는다.
 *
 * DO NOT
 * - `dibay_id_locked === true ? true : null` 같은 username_confirmed 추측을 다른 파일에 두지 않는다.
 * - 미확정 username 을 내정보 @handle·친구검색 publicId 로 노출하지 않는다.
 */

import { isAutoGeneratedDibayId, normalizeDibayIdInput } from "@/lib/auth/dibay-id-policy";
import { formatAtUsername } from "@/lib/users/user-label";

/** profiles @public-id 관련 최소 필드 — fetch·gate·UI 공통 */
export type ProfilePublicIdFields = {
  dibay_id?: string | null;
  dibay_id_locked?: boolean | null;
  username?: string | null;
  username_confirmed?: boolean | null;
};

export type PublicIdProfileView = {
  /** 기능 gate(친구추가·내정보 CTA·프로필 완성) */
  setupComplete: boolean;
  /** 확정 @handle — setupComplete 일 때만 */
  atDisplay: string | null;
  /** 프로필 수정 입력 seed(확정 전 draft 포함) */
  inputSeed: string;
  /** 검색·메신저 subtitle·publicId 노출용(확정만) */
  searchableId: string | null;
  locked: boolean;
};

function pickTrimmed(input: unknown): string | null {
  if (typeof input !== "string") return null;
  const trimmed = input.trim();
  return trimmed.length > 0 ? trimmed : null;
}

/** DB row → gate 입력. username_confirmed 누락 시 locked 로만 보수 추론. */
export function normalizeProfilePublicIdFields(
  row: ProfilePublicIdFields
): Required<Pick<ProfilePublicIdFields, "dibay_id" | "dibay_id_locked" | "username" | "username_confirmed">> {
  return {
    dibay_id: row.dibay_id ?? null,
    dibay_id_locked: row.dibay_id_locked ?? null,
    username: row.username ?? null,
    username_confirmed:
      row.username_confirmed === true || row.username_confirmed === false
        ? row.username_confirmed
        : row.dibay_id_locked === true
          ? true
          : null,
  };
}

/** dibay_id 우선, 없으면 username — @ 제거·소문자. auto dibay_* 는 null. */
export function resolveCanonicalPublicIdRaw(row: ProfilePublicIdFields | null | undefined): string | null {
  if (!row) return null;
  const raw = normalizeDibayIdInput(pickTrimmed(row.dibay_id) ?? pickTrimmed(row.username) ?? "");
  if (!raw || isAutoGeneratedDibayId(raw)) return null;
  return raw;
}

/** 친구검색·메신저 subtitle·publicId — 확정된 id 만 */
export function resolveSearchablePublicId(row: ProfilePublicIdFields | null | undefined): string | null {
  if (!row) return null;
  const normalized = normalizeProfilePublicIdFields(row);
  const dibay = pickTrimmed(normalized.dibay_id);
  if (dibay) {
    const id = normalizeDibayIdInput(dibay);
    return id && !isAutoGeneratedDibayId(id) ? id : null;
  }
  if (normalized.username_confirmed === true) {
    const username = normalizeDibayIdInput(pickTrimmed(normalized.username) ?? "");
    return username && !isAutoGeneratedDibayId(username) ? username : null;
  }
  return null;
}

/** @handle UI — 확정 public id 만 */
export function resolvePublicIdAtDisplay(row: ProfilePublicIdFields | null | undefined): string | null {
  const searchable = resolveSearchablePublicId(row);
  return searchable ? formatAtUsername(searchable) : null;
}

/** 프로필 수정·온보딩 입력 seed */
export function resolvePublicIdInputSeed(row: ProfilePublicIdFields | null | undefined): string {
  return resolveCanonicalPublicIdRaw(row) ?? "";
}

/** 검색 후보 eligibility — user-public-id-search 와 동일 */
export function isPublicIdSearchEligible(row: ProfilePublicIdFields | null | undefined): boolean {
  return resolveSearchablePublicId(row) != null;
}

/** 기능 gate 단일 진입점 */
export function isPublicIdSetupComplete(row: ProfilePublicIdFields | null | undefined): boolean {
  if (!row) return false;
  const normalized = normalizeProfilePublicIdFields(row);
  const canonical = resolveCanonicalPublicIdRaw(normalized);
  if (!canonical) return false;
  if (normalized.username_confirmed === false) return false;
  if (normalized.dibay_id_locked === true) return true;
  if (normalized.username_confirmed === true && pickTrimmed(normalized.username)) return true;
  return false;
}

/** 내정보·프로필수정 — 한 번에 */
export function evaluatePublicIdProfileView(row: ProfilePublicIdFields | null | undefined): PublicIdProfileView {
  const normalized = normalizeProfilePublicIdFields(row ?? {});
  const setupComplete = isPublicIdSetupComplete(normalized);
  return {
    setupComplete,
    atDisplay: setupComplete ? resolvePublicIdAtDisplay(normalized) : null,
    inputSeed: resolvePublicIdInputSeed(normalized),
    searchableId: resolveSearchablePublicId(normalized),
    locked: normalized.dibay_id_locked === true,
  };
}

/** @deprecated — normalizeProfilePublicIdFields 사용 */
export const profileFieldsForDibayIdComplete = normalizeProfilePublicIdFields;

/** @deprecated — isPublicIdSetupComplete 사용 */
export function isDibayIdComplete(row: ProfilePublicIdFields | null | undefined): boolean {
  return isPublicIdSetupComplete(row);
}
