/** DIBAY public @id — DB stores without leading @ */

export const DIBAY_ID_RE = /^[a-z0-9](?:[a-z0-9_.]{2,18}[a-z0-9])$/;

export const DIBAY_ID_RESERVED = new Set([
  "admin",
  "administrator",
  "support",
  "owner",
  "system",
  "official",
  "staff",
  "root",
  "mod",
  "help",
  "dibay",
  "samarket",
]);

const DEFAULT_DIBAY_AUTO_PATTERN = /^dibay_[a-f0-9]{6}$/;

export function normalizeDibayIdInput(v: unknown): string {
  return String(v ?? "")
    .trim()
    .toLowerCase()
    .replace(/^@+/, "");
}

export function isAutoGeneratedDibayId(value: string | null | undefined): boolean {
  const trimmed = typeof value === "string" ? value.trim().toLowerCase() : "";
  return Boolean(trimmed && DEFAULT_DIBAY_AUTO_PATTERN.test(trimmed));
}

export function isValidDibayIdFormat(normalized: string): boolean {
  if (!normalized || !DIBAY_ID_RE.test(normalized)) return false;
  if (DIBAY_ID_RESERVED.has(normalized)) return false;
  if (isAutoGeneratedDibayId(normalized)) return false;
  return true;
}
