import { isAutoGeneratedDibayId } from "@/lib/auth/dibay-id-policy";
import { isDibayIdComplete, type DibaySignupProfileInput } from "@/lib/auth/dibay-signup-status";

/** OAuth seed — provider nickname 없을 때 서버 기본 display_name (i18n: profile_default_display_name) */
export const DEFAULT_OAUTH_DISPLAY_NAME = "DIBAY 사용자";

export function pickTrimmedProfileField(input: unknown): string | null {
  if (typeof input !== "string") return null;
  const trimmed = input.trim();
  return trimmed.length > 0 ? trimmed : null;
}

export function resolveOAuthSeedDisplayName(nicknameCandidate: string | null | undefined): string {
  return pickTrimmedProfileField(nicknameCandidate) ?? DEFAULT_OAUTH_DISPLAY_NAME;
}

const DISPLAY_NAME_MIN = 2;
const DISPLAY_NAME_MAX = 20;

/** 표시 이름 유효 — auto dibay_* 제외, 2~20자 */
export function hasValidDisplayName(profile: {
  display_name?: string | null;
  nickname?: string | null;
} | null | undefined): boolean {
  if (!profile) return false;
  const name =
    pickTrimmedProfileField(profile.display_name) ?? pickTrimmedProfileField(profile.nickname);
  if (!name) return false;
  if (isAutoGeneratedDibayId(name)) return false;
  return name.length >= DISPLAY_NAME_MIN && name.length <= DISPLAY_NAME_MAX;
}

export function hasVerifiedPhone(profile: {
  phone_verified?: boolean | null;
  phone_verified_at?: string | null;
} | null | undefined): boolean {
  if (!profile) return false;
  return profile.phone_verified === true || Boolean(pickTrimmedProfileField(profile.phone_verified_at));
}

export { isDibayIdComplete };

export type ProfileFieldCheckInput = DibaySignupProfileInput & {
  nickname?: string | null;
  phone_verified?: boolean | null;
  phone_verified_at?: string | null;
  has_default_address?: boolean | null;
};
