import { isAutoGeneratedDibayId } from "@/lib/auth/dibay-id-policy";
import type { OAuthProfileSeed } from "@/lib/auth/oauth-profile-seed";

export type OAuthNicknameProfileInput = {
  onboarding_completed_at?: string | null;
  nickname?: string | null;
  display_name?: string | null;
};

function pickTrimmed(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : null;
}

function isLegacyAutoNickname(value: string | null | undefined): boolean {
  return isAutoGeneratedDibayId(value);
}

export function shouldRefreshNicknameFromOAuth(
  profile: OAuthNicknameProfileInput | null | undefined,
  nicknameCandidate: string | null | undefined
): boolean {
  if (profile?.onboarding_completed_at) return false;
  const candidate = pickTrimmed(nicknameCandidate);
  if (!candidate) return false;

  const nickname = pickTrimmed(profile?.nickname);
  const displayName = pickTrimmed(profile?.display_name);

  if (!nickname && !displayName) return true;
  if (isLegacyAutoNickname(nickname) || isLegacyAutoNickname(displayName)) return true;
  return false;
}

export function buildOAuthNicknamePatch(
  profile: OAuthNicknameProfileInput | null | undefined,
  seed: Pick<OAuthProfileSeed, "nicknameCandidate">
): { nickname?: string; display_name?: string } | null {
  if (!shouldRefreshNicknameFromOAuth(profile, seed.nicknameCandidate)) return null;
  const candidate = pickTrimmed(seed.nicknameCandidate);
  if (!candidate) return null;
  return { nickname: candidate, display_name: candidate };
}
