import type { BrowseMockStore } from "./types";

/**
 * 시뮬레이션 비즈 업체 목록.
 * slug 는 URL 에 사용 — 실서비스 전환 시 stores.slug 와 동일 역할.
 */
export const BROWSE_MOCK_STORES: BrowseMockStore[] = [
  {
    id: "mock-seoul-korean",
    slug: "seoul-korean-house",
    nameKo: "서울한식당",
    tagline: "김치찌개, 불고기, 제육볶음 전문",
    primarySlug: "restaurant",
    subSlug: "korean",
    regionLabel: "Angeles",
    status: "open",
    primaryNameKo: "식당",
    subNameKo: "한식",
    coverTint: "from-amber-700/90 to-orange-600/80",
    logoEmoji: "🍚",
    phone: "+63-900-000-0001",
    addressLine: "Angeles · 필리핀 (샘플 주소)",
    hoursSummary: "10:00–22:00 (연중무휴 · 시뮬)",
    deliveryAvailable: true,
    pickupAvailable: true,
    visitAvailable: true,
    reviewCount: 128,
    rating: 4.7,
    featuredItems: [
      { name: "김치찌개", price: 250 },
      { name: "불고기정식", price: 320 },
    ],
  },
  {
    id: "mock-mom-snack",
    slug: "mom-hand-snack",
    nameKo: "엄마손분식",
    tagline: "떡볶이, 김밥, 튀김 전문",
    primarySlug: "restaurant",
    subSlug: "korean",
    regionLabel: "Clark",
    status: "open",
    primaryNameKo: "식당",
    subNameKo: "한식",
    coverTint: "from-rose-600/90 to-pink-500/80",
    logoEmoji: "🍢",
    phone: "+63-900-000-0002",
    addressLine: "Clark · 필리핀 (샘플 주소)",
    hoursSummary: "11:00–21:00",
    deliveryAvailable: true,
    pickupAvailable: true,
    visitAvailable: true,
    reviewCount: 86,
    rating: 4.5,
    featuredItems: [
      { name: "떡볶이", price: 120 },
      { name: "참치김밥", price: 140 },
    ],
  },
  {
    id: "mock-hk-style",
    slug: "hk-style-house",
    nameKo: "홍콩반점 스타일 하우스",
    tagline: "짜장면, 짬뽕, 탕수육",
    primarySlug: "restaurant",
    subSlug: "chinese",
    regionLabel: "Angeles",
    status: "open",
    primaryNameKo: "식당",
    subNameKo: "중식",
    coverTint: "from-red-800/90 to-red-600/80",
    logoEmoji: "🥡",
    phone: "+63-900-000-0003",
    addressLine: "Angeles · 필리핀 (샘플 주소)",
    hoursSummary: "10:30–21:30",
    deliveryAvailable: true,
    pickupAvailable: true,
    visitAvailable: true,
    reviewCount: 210,
    rating: 4.6,
    featuredItems: [
      { name: "짜장면", price: 180 },
      { name: "짬뽕", price: 220 },
    ],
  },
  {
    id: "mock-china-wok",
    slug: "china-wok",
    nameKo: "차이나 웍",
    tagline: "볶음밥, 깐풍기, 마파두부",
    primarySlug: "restaurant",
    subSlug: "chinese",
    regionLabel: "Manila",
    status: "preparing",
    primaryNameKo: "식당",
    subNameKo: "중식",
    coverTint: "from-yellow-700/90 to-amber-600/80",
    logoEmoji: "🍳",
    phone: "+63-900-000-0004",
    addressLine: "Manila · Malate (샘플)",
    hoursSummary: "오픈 준비 중",
    deliveryAvailable: false,
    pickupAvailable: true,
    visitAvailable: false,
    reviewCount: 12,
    rating: 4.2,
    featuredItems: [
      { name: "볶음밥", price: 200 },
      { name: "마파두부", price: 260 },
    ],
  },
  {
    id: "mock-pasta-grill",
    slug: "pasta-grill-house",
    nameKo: "Pasta & Grill House",
    tagline: "파스타, 스테이크, 샐러드",
    primarySlug: "restaurant",
    subSlug: "western",
    regionLabel: "BGC",
    status: "open",
    primaryNameKo: "식당",
    subNameKo: "양식",
    coverTint: "from-emerald-800/90 to-teal-600/80",
    logoEmoji: "🍝",
    phone: "+63-900-000-0005",
    addressLine: "BGC · Taguig (샘플)",
    hoursSummary: "11:00–23:00",
    deliveryAvailable: true,
    pickupAvailable: true,
    visitAvailable: true,
    reviewCount: 340,
    rating: 4.8,
    featuredItems: [
      { name: "까보나라", price: 290 },
      { name: "비프스테이크", price: 680 },
    ],
  },
  {
    id: "mock-korea-snackbar",
    slug: "korea-snackbar",
    nameKo: "코리아 스낵바",
    tagline: "떡볶이, 순대, 라볶이",
    primarySlug: "restaurant",
    subSlug: "snack",
    regionLabel: "Quezon City",
    status: "open",
    primaryNameKo: "식당",
    subNameKo: "분식",
    coverTint: "from-orange-700/90 to-red-500/80",
    logoEmoji: "🌶️",
    phone: "+63-900-000-0006",
    addressLine: "Quezon City (샘플)",
    hoursSummary: "12:00–24:00",
    deliveryAvailable: true,
    pickupAvailable: true,
    visitAvailable: true,
    reviewCount: 95,
    rating: 4.4,
    featuredItems: [
      { name: "라볶이", price: 160 },
      { name: "순대", price: 170 },
    ],
  },
  {
    id: "mock-seoul-mart",
    slug: "seoul-mart",
    nameKo: "서울마트",
    tagline: "한인 식재료 한곳에",
    primarySlug: "mart",
    subSlug: "korean-mart",
    regionLabel: "Angeles",
    status: "open",
    primaryNameKo: "마트",
    subNameKo: "한인마트",
    coverTint: "from-green-800/90 to-lime-600/80",
    logoEmoji: "🏪",
    phone: "+63-900-000-0101",
    addressLine: "Angeles (샘플)",
    hoursSummary: "08:00–22:00",
    deliveryAvailable: true,
    pickupAvailable: true,
    visitAvailable: true,
    reviewCount: 402,
    rating: 4.5,
    featuredItems: [
      { name: "신라면", price: 45 },
      { name: "고추장", price: 180 },
    ],
  },
  {
    id: "mock-fresh-local",
    slug: "fresh-local-mart",
    nameKo: "Fresh Local Mart",
    tagline: "신선 로컬 식재료",
    primarySlug: "mart",
    subSlug: "local-mart",
    regionLabel: "Manila",
    status: "open",
    primaryNameKo: "마트",
    subNameKo: "로컬마트",
    coverTint: "from-lime-700/90 to-green-500/80",
    logoEmoji: "🥬",
    phone: "+63-900-000-0102",
    addressLine: "Manila (샘플)",
    hoursSummary: "07:00–21:00",
    deliveryAvailable: false,
    pickupAvailable: true,
    visitAvailable: true,
    reviewCount: 156,
    rating: 4.3,
    featuredItems: [
      { name: "계란 12구", price: 95 },
      { name: "바나나", price: 60 },
    ],
  },
  {
    id: "mock-tool-master",
    slug: "tool-master",
    nameKo: "Tool Master",
    tagline: "전동공구·공구 전문",
    primarySlug: "hardware",
    subSlug: "power-tools",
    regionLabel: "Cebu",
    status: "open",
    primaryNameKo: "공구류",
    subNameKo: "전동공구",
    coverTint: "from-slate-800/90 to-zinc-600/80",
    logoEmoji: "⚙️",
    phone: "+63-900-000-0201",
    addressLine: "Cebu (샘플)",
    hoursSummary: "09:00–19:00",
    deliveryAvailable: false,
    pickupAvailable: true,
    visitAvailable: true,
    reviewCount: 67,
    rating: 4.6,
    featuredItems: [
      { name: "전동드릴", price: 2200 },
      { name: "그라인더", price: 1800 },
    ],
  },
  {
    id: "mock-safety-build",
    slug: "safety-build",
    nameKo: "Safety Build",
    tagline: "안전용품·현장 장비",
    primarySlug: "hardware",
    subSlug: "safety",
    regionLabel: "Davao",
    status: "open",
    primaryNameKo: "공구류",
    subNameKo: "안전용품",
    coverTint: "from-yellow-600/90 to-amber-700/80",
    logoEmoji: "⛑️",
    phone: "+63-900-000-0202",
    addressLine: "Davao (샘플)",
    hoursSummary: "08:30–18:30",
    deliveryAvailable: true,
    pickupAvailable: true,
    visitAvailable: true,
    reviewCount: 44,
    rating: 4.5,
    featuredItems: [
      { name: "안전모", price: 350 },
      { name: "작업장갑", price: 80 },
    ],
  },
  {
    id: "mock-happy-pet",
    slug: "happy-pet-house",
    nameKo: "Happy Pet House",
    tagline: "사료·간식 전문",
    primarySlug: "pet",
    subSlug: "pet-food",
    regionLabel: "BGC",
    status: "open",
    primaryNameKo: "펫샵",
    subNameKo: "사료",
    coverTint: "from-violet-700/90 to-purple-500/80",
    logoEmoji: "🐶",
    phone: "+63-900-000-0301",
    addressLine: "BGC (샘플)",
    hoursSummary: "10:00–20:00",
    deliveryAvailable: true,
    pickupAvailable: true,
    visitAvailable: true,
    reviewCount: 189,
    rating: 4.7,
    featuredItems: [
      { name: "강아지 사료", price: 750 },
      { name: "고양이 사료", price: 680 },
    ],
  },
  {
    id: "mock-pet-groom",
    slug: "pet-grooming-care",
    nameKo: "Pet Grooming Care",
    tagline: "소형견 미용·케어",
    primarySlug: "pet",
    subSlug: "pet-groom",
    regionLabel: "Quezon City",
    status: "open",
    primaryNameKo: "펫샵",
    subNameKo: "미용",
    coverTint: "from-sky-700/90 to-cyan-500/80",
    logoEmoji: "✂️",
    phone: "+63-900-000-0302",
    addressLine: "Quezon City (샘플)",
    hoursSummary: "09:00–19:00 (예약)",
    deliveryAvailable: false,
    pickupAvailable: false,
    visitAvailable: true,
    reviewCount: 233,
    rating: 4.8,
    featuredItems: [
      { name: "소형견 미용", price: 600 },
      { name: "목욕", price: 350 },
    ],
  },
  {
    id: "mock-corner-coffee",
    slug: "corner-coffee-lab",
    nameKo: "코너 커피랩",
    tagline: "싱글오리진 드립·에스프레소",
    primarySlug: "cafe",
    subSlug: "coffee",
    regionLabel: "Makati",
    status: "open",
    primaryNameKo: "카페",
    subNameKo: "커피",
    coverTint: "from-stone-800/90 to-amber-900/80",
    logoEmoji: "☕",
    phone: "+63-900-000-0401",
    addressLine: "Makati (샘플)",
    hoursSummary: "07:30–21:00",
    deliveryAvailable: true,
    pickupAvailable: true,
    visitAvailable: true,
    reviewCount: 312,
    rating: 4.9,
    featuredItems: [
      { name: "아메리카노", price: 140 },
      { name: "카페라떼", price: 170 },
    ],
  },
];

const bySlug = new Map(BROWSE_MOCK_STORES.map((s) => [s.slug, s]));

export function getBrowseMockStoreBySlug(slug: string): BrowseMockStore | undefined {
  return bySlug.get(slug.trim());
}
